### ISSUE TITLE
Create an admin interface for creating `AttachmentType`s

### ISSUE THREAD

**Issue by jon-bell** [clowdr-app/clowdr-web-app#101]
Also probably need to automatically populate a base set of attachments when the conference is initialized

**Comment by pained** [comment]
I was testing adding attachments/media to a program item in the CSCW demo site but cannot since the "Media Link/Attachment Category" dropdown does not populate with any options. 

I'm not sure if this is the same interface referenced in this issue or if I should open a new issue. 

We would need to be able to test this media attachment feature since we want to be able to have not only Posters displayed but also video links embedded and ideally playable from the Clowdr page for each item.

<img width="521" alt="Screen Shot 2020-08-14 at 10 38 19 AM" src="https://user-images.githubusercontent.com/254765/90277579-b840ec80-de1a-11ea-97b5-af6611db6053.png">

**Comment by jon-bell** [comment]
@pained Right now the easiest fix is for you to just tell me which kinds of attachments you would like: posters and videos? We can add a feature to embed a video player for the video before CSCW.

**Comment by bcpierce00** [comment]
OK, added "External site" attachment type.

**Comment by pained** [comment]
@jon-bell Hi Jon, that would be fine. Our general chairs wanted the ability to have a link to a video on the page for a program item. So off the top of my head the following types of attachments are likely useful for CSCW:

1. Link to paper/slides (PDF or just website, e.g. ACM Digital Library)
2. Video embed (link to YouTube)
3. PDF (for attaching posters)
4. Link to poll for Q/A (e.g. sli.do)

Being able to populate some examples in our demo with these various aspects would really help with our planning.

**Comment by jon-bell** [comment]
@pained OK, as a quick-fix I created these attachment types for CSCW. Posters work best when uploaded as a graphic (PNG/JPG), because then they can be more easily rendered by browsers. We can make it so that the video is displayed as embedded in the page, but this will not be possible for another week or so due to development time commitments.

**Comment by pained** [comment]
@jon-bell that is just fine thanks. And good to know re: PNG/JPG. I'll convey this to the committee over here.

**Comment by pained** [comment]
This may need to be a different issue but: is it possible when a video link (e.g. YouTube) is added to render the embedded player so that a user doesn't have to leave Clowdr to watch the linked file?

**Comment by bcpierce00** [comment]
Please do make another issue for this!

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(We are working on how to implement this stuff in the new UI ready for SPLASH authors)
