### ISSUE TITLE
When editing the Tracks table and cancel editing, it won't automatically restore the original state

### ISSUE THREAD

**Issue by anniejingchen** [clowdr-app/clowdr-web-app#105]
When editing the Tracks table and cancel editing, it won't automatically restore the original state. Only when refreshing the table, it will return the original state.

* Init state

![image](https://user-images.githubusercontent.com/51510527/89484385-44844d00-d753-11ea-99ed-36796d424efe.png)

* When canceling edit
![image](https://user-images.githubusercontent.com/51510527/89484431-58c84a00-d753-11ea-9d8d-db400e34ab6b.png)
* After canceling edit

![image](https://user-images.githubusercontent.com/51510527/89484486-72699180-d753-11ea-9ea1-eb41216cf076.png)

* After refreshing

![image](https://user-images.githubusercontent.com/51510527/89484564-a1800300-d753-11ea-8820-00a6a0ba34ad.png)

**Comment by bingfeizh** [comment]
That's because the Checkbox value is updated when it is clicked, not when the save button clicked. If we press the cancel button, the update of the Checkbox is kept but not sent to the database. And when we refresh, the Checkbox value is updated from the database again. Maybe we need to define our own Checkbox...

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.
