### ISSUE TITLE
Saving paper from paper detail page, feature request

### ISSUE THREAD

**Issue by SaKa1979** [clowdr-app/clowdr-web-app#199]
It would be nice to be able to save a certain session/paper from its detail page. So I can filter it by Star at the program overview page later.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

(In the new UI, there is a "Followed Items" page that shows things you've starred. We will continue to improve the UX/UI in this area but I'm closing this issue in favour of tracking future development in other issues.)
