### ISSUE TITLE
Improved search

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#47]
We really want to be able to (a) search for anyone on the platform, not
  just people in the same top-level room as me, (b) search for anybody
  registered for the conference, not just people signed on to the platform
  right now, and (c) send a chat message to anybody I can search for…

  (JB: This is not hard. The ContextualActiveUsers already gets all of the presences and filters them to the current social space. So, the search bar could be set to search across all of the users.)

**Comment by jon-bell** [comment]
@anniejingchen This implementation is not acceptable.

* The behavior of the left user list should be: show the users in the current room. Now, it shows all users, regardless of what room they are in
* The code is extremely inefficient. On my 2019 MacBook Pro, loading the ICSE site now requires over 1GB of RAM, and expanding the total list of users in the sidebar takes 30-40 seconds. Please do not make an extra query to retrieve all UserProfiles: the correct way to do this is to call `getUsers` in `withAuthentication`. However, the sidebar really needs to be showing the `UserPresence`s - I think that a better fix will be to search on-demand as the user types in the box.

Please let me know if you can resolve this today, if not, I will revert the commit so that `master` continues to have the correct behavior for the sidebar.

Thanks

**Comment by bcpierce00** [comment]
Just to clarify, here is my understanding of how the left user list should behave:

- The list displayed on the left should be just as it always has been -- i.e., it should show just users in the current room.
- When the user starts a search by typing in the search bar, the search results should be displayed incrementally (i.e., at any moment, the list of results under the search bar is showing all matching names, and the list is updated as the user types)
- The list of results should include (in this order)
      - all rooms whose names match
      - all matching users that are in the current room
      - all matching users that are not in the current room

**Comment by jon-bell** [comment]
I just reversed the commit

**Comment by bcpierce00** [comment]
@anniejingchen, will we have this for ICFP?

**Comment by anniejingchen** [comment]
@bcpierce00 Hi, Benjamin, I have a question about where to display the found user. After we find a user who we would like to send a DM and click the name, where will it be displayed in order to send her/him a DM? Should they be displayed on the left and replace the original list for the current room?  (The pictures are about how the searching work for a room now). However, based on what you mentioned above, the list displayed on the left should show just users in the current room. If this is the case, I am a little confusing. Could you give me more explanation? Thanks.
![image](https://user-images.githubusercontent.com/51510527/90093488-93485e80-dce0-11ea-9af0-f43d00ea734d.png)![image](https://user-images.githubusercontent.com/51510527/90093497-980d1280-dce0-11ea-95b3-541c2524ae8c.png)

**Comment by jon-bell** [comment]
What about: Show the user in the drop down for the search (as shown on the lefT), and pressing “enter” opens the tooltip to display the user’s profile, but does not filter the list of users in the current room.

**Comment by jon-bell** [comment]
I just implemented this in the new chat search. All that is left is to clean it up to show the user's profile in the popover when it's searching.

**Comment by bcpierce00** [comment]
This is looking great!  One issue is that the search bar is hard to find at the bottom of the screen and its placement makes it hard to guess that it can be used for things besides chats.  Could we move it to the top-level menu bar or some other more global place?
