### ISSUE TITLE
Audio-only chatting

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr-web-app#54]
Video rooms should let you join without a camera, and have audio only. Right now I think that it will just hang if you don't have a camera, or click "don't allow" to the prompt for permission

**Comment by Chobbes** [comment]
This is still an issue. During setup for ICFP it sounded like it wouldn't be an issue anymore, but it's still a problem.

**Comment by jon-bell** [comment]
@Chobbes In the meantime, we have added much better error handling for this (it hasn't yet been deployed - see #119 ). We are aware that this is still an issue, which is why it is still open. I am happy to point you to the right place in the code if you have time to address it immediately, otherwise it will likely remain fairly low priority.

**Comment by EdNutting** [comment]
Closing as the new UI has been developed after this issue was opened and this issue relates only to the old UI.

The new UI fixed this.
